# coding: utf-8

"""
    SQLMap Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import sqlmap_client
from sqlmap_client.models.get_task_options_response import GetTaskOptionsResponse  # noqa: E501
from sqlmap_client.rest import ApiException

class TestGetTaskOptionsResponse(unittest.TestCase):
    """GetTaskOptionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetTaskOptionsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = sqlmap_client.models.get_task_options_response.GetTaskOptionsResponse()  # noqa: E501
        if include_optional :
            return GetTaskOptionsResponse(
                success = True, 
                options = None
            )
        else :
            return GetTaskOptionsResponse(
                success = True,
                options = None,
        )

    def testGetTaskOptionsResponse(self):
        """Test GetTaskOptionsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
