
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T20:20:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "050f3368ac881e7593daf8c8306c8a6e389909df",
 "version": "v1.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
