# coding: utf-8

"""
    SQLMap Server API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from sqlmap_client.configuration import Configuration


class CreateTaskResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'success': 'bool',
        'taskid': 'str'
    }

    attribute_map = {
        'success': 'success',
        'taskid': 'taskid'
    }

    def __init__(self, success=None, taskid=None, local_vars_configuration=None):  # noqa: E501
        """CreateTaskResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._success = None
        self._taskid = None
        self.discriminator = None

        self.success = success
        self.taskid = taskid

    @property
    def success(self):
        """Gets the success of this CreateTaskResponse.  # noqa: E501


        :return: The success of this CreateTaskResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this CreateTaskResponse.


        :param success: The success of this CreateTaskResponse.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and success is None:  # noqa: E501
            raise ValueError("Invalid value for `success`, must not be `None`")  # noqa: E501

        self._success = success

    @property
    def taskid(self):
        """Gets the taskid of this CreateTaskResponse.  # noqa: E501


        :return: The taskid of this CreateTaskResponse.  # noqa: E501
        :rtype: str
        """
        return self._taskid

    @taskid.setter
    def taskid(self, taskid):
        """Sets the taskid of this CreateTaskResponse.


        :param taskid: The taskid of this CreateTaskResponse.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and taskid is None:  # noqa: E501
            raise ValueError("Invalid value for `taskid`, must not be `None`")  # noqa: E501

        self._taskid = taskid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateTaskResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CreateTaskResponse):
            return True

        return self.to_dict() != other.to_dict()
