
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-05T18:19:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3567aeb687d3d0c853243d2d482d90aeb2cf1292",
 "version": "0.5.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
