# coding: utf-8

"""
    Managed Ray API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class SessionUpOptions(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'project_id': 'str',
        'name': 'str',
        'cluster_config': 'WriteClusterConfig',
        'cloud_id': 'str'
    }

    attribute_map = {
        'project_id': 'project_id',
        'name': 'name',
        'cluster_config': 'cluster_config',
        'cloud_id': 'cloud_id'
    }

    def __init__(self, project_id=None, name=None, cluster_config=None, cloud_id=None, local_vars_configuration=None):  # noqa: E501
        """SessionUpOptions - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._project_id = None
        self._name = None
        self._cluster_config = None
        self._cloud_id = None
        self.discriminator = None

        self.project_id = project_id
        self.name = name
        if cluster_config is not None:
            self.cluster_config = cluster_config
        self.cloud_id = cloud_id

    @property
    def project_id(self):
        """Gets the project_id of this SessionUpOptions.  # noqa: E501


        :return: The project_id of this SessionUpOptions.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this SessionUpOptions.


        :param project_id: The project_id of this SessionUpOptions.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and project_id is None:  # noqa: E501
            raise ValueError("Invalid value for `project_id`, must not be `None`")  # noqa: E501

        self._project_id = project_id

    @property
    def name(self):
        """Gets the name of this SessionUpOptions.  # noqa: E501


        :return: The name of this SessionUpOptions.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SessionUpOptions.


        :param name: The name of this SessionUpOptions.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def cluster_config(self):
        """Gets the cluster_config of this SessionUpOptions.  # noqa: E501


        :return: The cluster_config of this SessionUpOptions.  # noqa: E501
        :rtype: WriteClusterConfig
        """
        return self._cluster_config

    @cluster_config.setter
    def cluster_config(self, cluster_config):
        """Sets the cluster_config of this SessionUpOptions.


        :param cluster_config: The cluster_config of this SessionUpOptions.  # noqa: E501
        :type: WriteClusterConfig
        """

        self._cluster_config = cluster_config

    @property
    def cloud_id(self):
        """Gets the cloud_id of this SessionUpOptions.  # noqa: E501


        :return: The cloud_id of this SessionUpOptions.  # noqa: E501
        :rtype: str
        """
        return self._cloud_id

    @cloud_id.setter
    def cloud_id(self, cloud_id):
        """Sets the cloud_id of this SessionUpOptions.


        :param cloud_id: The cloud_id of this SessionUpOptions.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and cloud_id is None:  # noqa: E501
            raise ValueError("Invalid value for `cloud_id`, must not be `None`")  # noqa: E501

        self._cloud_id = cloud_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SessionUpOptions):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SessionUpOptions):
            return True

        return self.to_dict() != other.to_dict()
