# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 21:45


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_categorysegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pages',
        ),
    ]
