# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-11 12:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filefields', '0008_auto_20190501_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='Is lock?'),
        ),
    ]
