# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 17:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181026_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_free',
        ),
    ]
