# -*- coding: utf-8 -*-

"""
    my_countries_api_123456

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from my_countries_api_123456.decorators import lazy_property
from my_countries_api_123456.configuration import Configuration
from my_countries_api_123456.controllers.countries_controller import CountriesController


class MyCountriesApi123456Client(object):

    config = Configuration

    @lazy_property
    def countries(self):
        return CountriesController()


