
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T22:51:18+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "703a3d69dcc38e5ba77560fdb95531a714aed791",
 "version": "2.0.1-3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
