
ENCRYPTION_KEY_FILE = '.szczypiorek_encryption_key'

ENCRYPTION_KEY_ENV = 'SZCZYPIOREK_ENCRYPTION_KEY'

ENCRYPTION_KEY_LENGTH = 128

ENVIRONMENT_GPG = 'SZCZYPIOREK_ENVIRONMENT_GPG'

ENVIRONMENT_GPG_FILE = 'SZCZYPIOREK_ENVIRONMENT_GPG_FILE'
