
# This file was generated by '_versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T15:24:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "eeaf088bf04851a3c2a44663199c92a2cc4fd7b9",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
