"""
This type stub file was generated by pyright.
"""

from distutils.util import Mixin2to3 as _Mixin2to3
from lib2to3.refactor import RefactoringTool

"""
Customized Mixin2to3 support:

 - adds support for converting doctests
"""
class DistutilsRefactoringTool(RefactoringTool):
    def log_error(self, msg, *args, **kw):
        ...
    
    def log_message(self, msg, *args):
        ...
    
    def log_debug(self, msg, *args):
        ...
    


class Mixin2to3(_Mixin2to3):
    def run_2to3(self, files, doctests=...):
        ...
    


