
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T15:50:15-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4b555501f218ed65633e00f2cbbc6b069fa1c2b",
 "version": "3.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
