# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-29 17:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_is_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maximum_use_aparnik_bon_value',
            field=models.IntegerField(default=-1, help_text='If the number is set to -1, then the value in the settings will apply, If the number is set to -2, then no limitation execution.', verbose_name='Maximum use aparnik bon'),
        ),
    ]
