from enum import IntEnum
import pygame


class PygameEvent(IntEnum):
    ACTIVEEVENT = pygame.ACTIVEEVENT
    AUDIODEVICEADDED = pygame.AUDIODEVICEADDED
    AUDIODEVICEREMOVED = pygame.AUDIODEVICEREMOVED
    CONTROLLERAXISMOTION = pygame.CONTROLLERAXISMOTION
    CONTROLLERBUTTONDOWN = pygame.CONTROLLERBUTTONDOWN
    CONTROLLERBUTTONUP = pygame.CONTROLLERBUTTONUP
    CONTROLLERDEVICEADDED = pygame.CONTROLLERDEVICEADDED
    CONTROLLERDEVICEREMOVED = pygame.CONTROLLERDEVICEREMOVED
    CONTROLLERDEVICEREMAPPED = pygame.CONTROLLERDEVICEREMAPPED
    DROPFILE = pygame.DROPFILE
    DROPTEXT = pygame.DROPTEXT
    DROPBEGIN = pygame.DROPBEGIN
    DROPCOMPLETE = pygame.DROPCOMPLETE
    FINGERMOTION = pygame.FINGERMOTION
    FINGERDOWN = pygame.FINGERDOWN
    FINGERUP = pygame.FINGERUP
    KEYDOWN = pygame.KEYDOWN
    KEYUP = pygame.KEYUP
    JOYAXISMOTION = pygame.JOYAXISMOTION
    JOYBALLMOTION = pygame.JOYBALLMOTION
    JOYHATMOTION = pygame.JOYHATMOTION
    JOYBUTTONDOWN = pygame.JOYBUTTONDOWN
    JOYBUTTONUP = pygame.JOYBUTTONUP
    JOYDEVICEADDED = pygame.JOYDEVICEADDED
    JOYDEVICEREMOVED = pygame.JOYDEVICEREMOVED
    MIDIIN = pygame.MIDIIN
    MIDIOUT = pygame.MIDIOUT
    MOUSEMOTION = pygame.MOUSEMOTION
    MOUSEBUTTONDOWN = pygame.MOUSEBUTTONDOWN
    MOUSEBUTTONUP = pygame.MOUSEBUTTONUP
    MOUSEWHEEL = pygame.MOUSEWHEEL
    MULTIGESTURE = pygame.MULTIGESTURE
    NOEVENT = pygame.NOEVENT
    QUIT = pygame.QUIT
    SYSWMEVENT = pygame.SYSWMEVENT
    TEXTEDITING = pygame.TEXTEDITING
    TEXTINPUT = pygame.TEXTINPUT
    VIDEORESIZE = pygame.VIDEORESIZE
    VIDEOEXPOSE = pygame.VIDEOEXPOSE
    WINDOWSHOWN = pygame.WINDOWSHOWN
    WINDOWHIDDEN = pygame.WINDOWHIDDEN
    WINDOWEXPOSED = pygame.WINDOWEXPOSED
    WINDOWMOVED = pygame.WINDOWMOVED
    WINDOWRESIZED = pygame.WINDOWRESIZED
    WINDOWSIZECHANGED = pygame.WINDOWSIZECHANGED
    WINDOWMINIMIZED = pygame.WINDOWMINIMIZED
    WINDOWMAXIMIZED = pygame.WINDOWMAXIMIZED
    WINDOWRESTORED = pygame.WINDOWRESTORED
    WINDOWENTER = pygame.WINDOWENTER
    WINDOWLEAVE = pygame.WINDOWLEAVE
    WINDOWFOCUSGAINED = pygame.WINDOWFOCUSGAINED
    WINDOWFOCUSLOST = pygame.WINDOWFOCUSLOST
    WINDOWCLOSE = pygame.WINDOWCLOSE
    WINDOWTAKEFOCUS = pygame.WINDOWTAKEFOCUS
    WINDOWHITTEST = pygame.WINDOWHITTEST

    USEREVENT = pygame.USEREVENT
