# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-05 15:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparnik_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
