# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-19 17:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparnik_users', '0018_auto_20190319_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username_mention',
            field=models.CharField(default='a', max_length=100, unique=True, verbose_name='Username for mention'),
        ),
    ]
