
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-01T21:42:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b375b1d9189f125828fdabbf2d329e5b1d04ff21",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
