
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-31T01:40:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b945db751e13f4bd8b96094276940969c2649ba4",
 "version": "0.18.2a1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
