
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-07T10:33:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7af78760aa3bc3c649620ca299fd4c2657c9851b",
 "version": "2.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
