
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-07T05:23:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f1d0dea8515adb5676b52dd9ad3778152d34c12",
 "version": "0.6.2.post.dev64"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
