# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-28 16:46


import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_basecourse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecourse',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='\\u062a\\u0648\\u0636\\u06cc\\u062d\\u0627\\u062a'),
        ),
    ]
