# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-28 10:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosales', '0002_cosale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosale',
            name='status',
            field=models.CharField(choices=[('C', 'Cleared'), ('NC', 'Not Cleared'), ('RSHBR', 'The request for settlement has been received'), ('OC', 'Order Cancel')], default='NC', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cosalehistory',
            name='status',
            field=models.CharField(choices=[('C', 'Cleared'), ('NC', 'Not Cleared'), ('RSHBR', 'The request for settlement has been received'), ('OC', 'Order Cancel')], default='NC', max_length=10, verbose_name='Status'),
        ),
    ]
