
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T14:22:05+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "28ce5d5e334aba78c76746a19320d3c2076f7cc4",
 "version": "2.4.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
