
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-24T11:46:59-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "d62a84b85cabee2d3a394c7e5e9e068c6ea4da35",
 "version": "1.19.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
