
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-31T18:25:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b466b2b42c9f21ad69c39e28e03e22a496fa2d37",
 "version": "2.4.27.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
