# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"try": "00_core.ipynb",
         "except": "00_core.ipynb",
         "img": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://feihuidiqiu.github.io/cc_nbdev_template/"

git_url = "https://github.com/feihuidiqiu/cc_nbdev_template/tree/master/"

def custom_doc_links(name): return None
