
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T06:24:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f86f15d01097b1c4ea0cbb84a0ebb34a1e038ebf",
 "version": "0.6.2.post.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
