# -*- coding: utf-8 -*-

"""
    countries_api

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from countries_api.decorators import lazy_property
from countries_api.configuration import Configuration
from countries_api.controllers.countries_controller import CountriesController


class CountriesApiClient(object):

    config = Configuration

    @lazy_property
    def countries(self):
        return CountriesController()


