
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T12:03:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e96a840887eb8c5d09c007cf458dbec2900dde3e",
 "version": "0.1.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
