
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T23:02:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1560973b88a5549d1b969ccb62b1c19295a1d519",
 "version": "0.1.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
