
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T00:52:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6257bd5d405111f3abc6ae3a2c2d5fa26f582c61",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
