
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T15:44:58-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfe36fca6f7e3afbf49ad63eb7f1865faaca2659",
 "version": "0.25.34"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
