# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-26 10:44


import aparnik.contrib.users.models
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aparnik_users', '0023_auto_20190526_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelogin',
            name='device_type',
            field=django_enumfield.db.fields.EnumField(default=0, blank=True, enum=aparnik.contrib.users.models.DeviceType, null=True, verbose_name='Device Type'),
        ),
    ]
