
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T19:02:38-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "03f4b3396a101abe28059d1dcffbf2dfcee5cf09",
 "version": "v1.1.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
