
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T14:36:31-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "528cef1ae68f74f871c899a5e8a41d4f114209b3",
 "version": "4.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
