
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T20:07:47-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ee816b26a8df171f989b6bb2b48b6e3a6d5207e",
 "version": "0.8.241"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
