
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-03T02:46:16+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8554fb72d6e4f4e6bb340b51fe557bb8160bdf59",
 "version": "0.5.dev2101"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
