#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['beautifulsoup4>=4.9.1', 'html5lib>=1.1', 'requests>=2.24.0']

setup(name='vgmusic',
      version='0.1.0a0',
      description='Python API for vgmusic.com.',
      author='Ong Yong Xin',
      author_email='ongyongxin2020+github@gmail.com',
      url='https://github.com/ongyx/vgmusic',
      py_modules=['vgmusic'],
      install_requires=install_requires,
      python_requires='>=3.6',
     )
