# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-25 15:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filefields', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('basereview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.BaseReview')),
                ('files', models.ManyToManyField(blank=True, to='filefields.FileField', verbose_name='Files')),
            ],
            options={
                'verbose_name': 'Question Answer',
                'verbose_name_plural': 'Questions Answers',
            },
            bases=('reviews.basereview',),
        ),
    ]
