# Generated by Django 2.2 on 2019-06-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionanswers', '0007_auto_20190613_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa',
            options={'verbose_name': 'پرسش و پاسخ', 'verbose_name_plural': 'پرسش و پاسخ ها'},
        ),
        migrations.AlterField(
            model_name='qa',
            name='files',
            field=models.ManyToManyField(blank=True, to='filefields.FileField', verbose_name='فایل ها'),
        ),
        migrations.AlterField(
            model_name='qa',
            name='model_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers_set', to='basemodels.BaseModel', verbose_name='چه چیز را نمایش دهد؟'),
        ),
    ]
