
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T18:39:15-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2daab3429a31f4e7edda801c0aae1cb026a95451",
 "version": "4.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
