
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-07T18:49:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "591a274c60a72623b6cbf45abad07ee52022652a",
 "version": "0.1.97"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
