# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-17 17:22


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190517_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSystem',
            fields=[
            ],
            options={
                'verbose_name': 'Notification System',
                'manager_inheritance_from_future': True,
                'proxy': True,
                'verbose_name_plural': 'Notifications System',
                'indexes': [],
            },
            bases=('notifications.notification',),
        ),
    ]
