
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T11:01:02+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "10ca9c3b2a8b049a68b8dd9bf0b0e5587be65736",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
