# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 20:59


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0003_basemodel_update_needed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMe',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.BaseModel')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('model_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifyme_model', to='basemodels.BaseModel', verbose_name='Model')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifyme_user', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notify Me',
                'verbose_name_plural': 'Notifies Me',
            },
            bases=('basemodels.basemodel',),
        ),
    ]
