# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-19 10:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190129_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Draft'),
        ),
    ]
