# Generated by Django 2.2 on 2020-02-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filefields', '0013_auto_20190714_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefield',
            name='password',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='رمز عبور'),
        ),
    ]
