#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pyboat']

package_data = \
{'': ['*'], 'pyboat': ['ui/*']}

install_requires = \
['numpy >=1.18',
 'scipy >=1.4',
 'matplotlib >=3.1',
 'pandas >=0.25',
 'PyQt5 >=5.9.5']

entry_points = \
{'console_scripts': ['pyboat = pyboat:main']}

setup(name='pyboat',
      version='0.9.1',
      description='pyBOAT - A Biological Oscillations Analysis Toolkit ',
      author='Gregor Mönke',
      author_email='gregor.moenke@embl.de',
      url='https://github.com/tensionhead/pyBOAT',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3.6',
     )
