
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-01T20:53:49-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ddf4df90db147365d407aea2ca5a26b30a2f2e13",
 "version": "v0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
