
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-08T10:24:55+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "c81e44b6ca23712660f23e6c0e417dd130337c3d",
 "version": "2.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
