# Generated by Django 2.2 on 2019-06-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20190615_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_for_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Description for admin'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_result',
            field=models.TextField(blank=True, null=True, verbose_name='Sent result'),
        ),
    ]
