
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T17:05:34-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "67a2a7e9ae126028e44a028feb3de6998b5e2f72",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
