# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 14:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparnik_users', '0012_auto_20190211_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_mention',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Username for mention'),
        ),
    ]
