# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-26 16:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosale',
            name='status',
            field=models.CharField(choices=[('C', 'Cleared'), ('NC', 'Not Cleared'), ('RSHBR', 'The request for settlement has been received')], default='NC', max_length=10, verbose_name='Status'),
        ),
    ]
