# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-15 13:40


from django.db import migrations


def remove_all(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    CoSale = apps.get_model('cosales', 'CoSale')

    CoSale.objects.all().delete()

    CoSaleHistory = apps.get_model('cosales', 'CoSaleHistory')

    CoSaleHistory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cosales', '0003_auto_20190128_1056'),
    ]

    operations = [
        migrations.RunPython(remove_all, reverse_code=migrations.RunPython.noop),
    ]
