
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-21T14:46:15+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5505ed91cc106632d5b2408ab84ce3f0d2996a05",
 "version": "0.3.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
