
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-09T14:33:13+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "66d474bb85632a81bbc93ab0d9ea2c248e56a1ec",
 "version": "2.0.50.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
