
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T22:14:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a26151815aa29b475995947cc4cec7fb48a54d48",
 "version": "v2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
