
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T17:07:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "350dbf9d283b76cbf40bdb4b12f437e4c12bc90d",
 "version": "9.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
