
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-21T21:47:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a0888edade48fcfe13ef0a4c1667fe76c5a13635",
 "version": "v1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
