# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-05 13:14


from django.db import migrations


def add_keys(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Setting = apps.get_model('settings', 'Setting')

    key = ''
    try:
        key = 'COURSE_IGNORE_IN_LIST_IDS'
        Setting.objects.get(key=key)
    except Exception:
        Setting.objects.create(
            title='دوره هایی که در لیست نمی آیند',
            key=key,
            value='',
            value_type='s',
            is_show=False,
            is_variable_in_home=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20181210_1432'),
    ]

    operations = [
        migrations.RunPython(add_keys, reverse_code=migrations.RunPython.noop),
    ]
