# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-23 10:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aparnik_users', '0020_auto_20190319_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_national_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company national number'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company registeration number'),
        ),
    ]
