__title__ = "youcab"
__description__ = "Converts MeCab parsing results to Python objects."
__url__ = "https://github.com/poyo46/youcab"
__version__ = "0.1.3"
__author__ = "poyo46"
__author_email__ = "poyo4rock@gmail.com"
__license__ = "BSD-3-Clause"
__copyright__ = "Copyright 2021 poyo46"
