# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-06 11:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update At')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL, verbose_name='Invite')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_by', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
            ],
        ),
    ]
