
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-31T15:44:52+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b880ffabfa4f056689549d1722154ec97e7cd3e1",
 "version": "2.4.27.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
