
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3e0df68914578ad43c06a43aa852343d625e3b50",
 "version": "0.6.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
