
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-01T16:59:08+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "244d3ad32cc79225fe0ebb9ecb0a54ab465520c7",
 "version": "0.7.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
