
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T13:51:26-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dc93d1090865f47e3f6694828f9929bbe34a886",
 "version": "0.4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
