# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 21:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slider_obj',
        ),
    ]
