# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-13 17:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181202_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('sh', 'Shippable'), ('dw', 'Downloadable')], max_length=10, verbose_name='Delivery type'),
        ),
    ]
