
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T18:22:50-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e55a212db8ec2360f71810e58e0279333115e6c",
 "version": "v0.2.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
