# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-01 11:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20190501_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='file',
            name='password',
        ),
    ]
