
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-07T14:14:57+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "84f58dd2e04ce76b2dfaec32d2546440836c503d",
 "version": "0.0.81"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
