# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 15:36


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0006_auto_20181211_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagulous_BaseModel_tags',
            new_name='Tag',
        ),
    ]
