
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-03T23:49:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3bec9c0338948c08f16ecba8612bd77bb4d32063",
 "version": "0.6.2.post.dev54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
