# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-26 11:32


from django.db import migrations


def remove_all_records(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Object = apps.get_model('contactus', 'ContactUs')
    Object.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20181125_2227'),
    ]

    operations = [
        migrations.RunPython(remove_all_records, reverse_code=migrations.RunPython.noop),
    ]
