
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-28T14:16:26-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d4f551d849dbf0189ce4bb1a4aa075c54f7ea4d",
 "version": "v1.1.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
