fred_countries_currencies = {
    'Australia': 'AUD',
    'Austria': 'ATS',
    'Belgium': 'BEF',
    'Brazil': 'BRL',
    'Canada': 'CAD',
    'China': 'CNY',
    'Denmark': 'DKK',
    'Euro': 'EUR',
    'Finland': 'FIM',
    'France': 'FRF',
    'Germany': 'DEM',
    'Greece': 'GRD',
    'Hong Kong': 'HKD',
    'Ireland': 'IEP',
    'Italy': 'ITL',
    'India': 'INR',
    'Japan': 'JPY',
    'Malaysia': 'MYR',
    'Mexico': 'MXN',
    'Norway': 'NOK',
    'Netherlands': 'NLG',
    'Portugal': 'PTE',
    'Singapore': 'SGD',
    'South Korea': 'KRW',
    'South Africa': 'ZAR',
    'Spain': 'ESP',
    'Sri Lanka': 'LKR',
    'Sweden': 'SEK',
    'Switzerland': 'CHF',
    'Taiwan': 'TWD',
    'Thailand': 'THB',
    'Venezuela': 'VEF',
    'New Zealand': 'NZD',
    'U.K.': 'GBP'
}

oecd_countries_currencies = {
    'AUS': 'AUD',
    'BRA': 'BRL',
    'CAN': 'CAD',
    'CHE': 'CHF',
    'CHL': 'CLP',
    'CHN': "CNY",
    'COL': 'COP',
    'CRI': 'CRC',
    'CZE': 'CZK',
    'DNK': 'DKK',
    'EA19': 'EUR',
    'GBR': 'GBP',
    'HUN': 'HUF',
    'IDN': 'IDR',
    'IND': 'INR',
    'ISL': 'ISK',
    'ISR': 'ILS',
    'JPN': 'JPY',
    'KOR': 'KRW',
    'LVA': 'LVL',
    'MEX': 'MXN',
    'NOR': 'NOK',
    'NZL': 'NZD',
    'POL': 'PLN',
    'RUS': 'RUB',
    'SDR': 'XDR',
    'SWE': 'SEK',
    'TUR': 'TRY',
    'ZAF': 'ZAR'
}
