# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-25 19:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0002_button_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='icon_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Icon color'),
        ),
    ]
