# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jomiel_messages/protobuf/v1beta1/message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jomiel_messages.protobuf.v1beta1 import media_pb2 as jomiel__messages_dot_protobuf_dot_v1beta1_dot_media__pb2
from jomiel_messages.protobuf.v1beta1 import status_pb2 as jomiel__messages_dot_protobuf_dot_v1beta1_dot_status__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jomiel_messages/protobuf/v1beta1/message.proto',
  package='jomiel_messages.protobuf.v1beta1',
  syntax='proto3',
  serialized_options=b'\n!io.github.jomiel.protobuf.v1beta1B\014MessageProtoP\001Z\027jomiel/protobuf/v1beta1\252\002\027Jomiel.ProtoBuf.V1Beta1\312\002\027Jomiel\\ProtoBuf\\V1beta1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.jomiel_messages/protobuf/v1beta1/message.proto\x12 jomiel_messages.protobuf.v1beta1\x1a,jomiel_messages/protobuf/v1beta1/media.proto\x1a-jomiel_messages/protobuf/v1beta1/status.proto\"U\n\x07Inquiry\x12?\n\x05media\x18\x01 \x01(\x0b\x32..jomiel_messages.protobuf.v1beta1.MediaInquiryH\x00\x42\t\n\x07inquiry\"\x9a\x01\n\x08Response\x12@\n\x05media\x18\x01 \x01(\x0b\x32/.jomiel_messages.protobuf.v1beta1.MediaResponseH\x00\x12@\n\x06status\x18\x02 \x01(\x0b\x32\x30.jomiel_messages.protobuf.v1beta1.ResponseStatusB\n\n\x08responseB\x80\x01\n!io.github.jomiel.protobuf.v1beta1B\x0cMessageProtoP\x01Z\x17jomiel/protobuf/v1beta1\xaa\x02\x17Jomiel.ProtoBuf.V1Beta1\xca\x02\x17Jomiel\\ProtoBuf\\V1beta1b\x06proto3'
  ,
  dependencies=[jomiel__messages_dot_protobuf_dot_v1beta1_dot_media__pb2.DESCRIPTOR,jomiel__messages_dot_protobuf_dot_v1beta1_dot_status__pb2.DESCRIPTOR,])




_INQUIRY = _descriptor.Descriptor(
  name='Inquiry',
  full_name='jomiel_messages.protobuf.v1beta1.Inquiry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='media', full_name='jomiel_messages.protobuf.v1beta1.Inquiry.media', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='inquiry', full_name='jomiel_messages.protobuf.v1beta1.Inquiry.inquiry',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=177,
  serialized_end=262,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='jomiel_messages.protobuf.v1beta1.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='media', full_name='jomiel_messages.protobuf.v1beta1.Response.media', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='jomiel_messages.protobuf.v1beta1.Response.status', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='jomiel_messages.protobuf.v1beta1.Response.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=265,
  serialized_end=419,
)

_INQUIRY.fields_by_name['media'].message_type = jomiel__messages_dot_protobuf_dot_v1beta1_dot_media__pb2._MEDIAINQUIRY
_INQUIRY.oneofs_by_name['inquiry'].fields.append(
  _INQUIRY.fields_by_name['media'])
_INQUIRY.fields_by_name['media'].containing_oneof = _INQUIRY.oneofs_by_name['inquiry']
_RESPONSE.fields_by_name['media'].message_type = jomiel__messages_dot_protobuf_dot_v1beta1_dot_media__pb2._MEDIARESPONSE
_RESPONSE.fields_by_name['status'].message_type = jomiel__messages_dot_protobuf_dot_v1beta1_dot_status__pb2._RESPONSESTATUS
_RESPONSE.oneofs_by_name['response'].fields.append(
  _RESPONSE.fields_by_name['media'])
_RESPONSE.fields_by_name['media'].containing_oneof = _RESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['Inquiry'] = _INQUIRY
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Inquiry = _reflection.GeneratedProtocolMessageType('Inquiry', (_message.Message,), {
  'DESCRIPTOR' : _INQUIRY,
  '__module__' : 'jomiel_messages.protobuf.v1beta1.message_pb2'
  # @@protoc_insertion_point(class_scope:jomiel_messages.protobuf.v1beta1.Inquiry)
  })
_sym_db.RegisterMessage(Inquiry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'jomiel_messages.protobuf.v1beta1.message_pb2'
  # @@protoc_insertion_point(class_scope:jomiel_messages.protobuf.v1beta1.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
