from .condition import ExtendCondition
from .filetype import RegisterFileType
from .instance import AddMethodToInstance
from .reporter import RegisterReporter
from .setup import AddSetupItem
from .test import ExtendTest
from .testenity import AddTestEntityMember
from .testers import AddTester
from .testrun import ExtendTestRun
from .version import AuTestVersion
from .when import AddWhenFunction
