# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-09 21:40


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0004_auto_20181103_2233'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.BaseModel')),
                ('account_number', models.CharField(max_length=255, verbose_name='Account Number')),
                ('shaba_number', models.CharField(max_length=255, verbose_name='Shaba Number')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'manager_inheritance_from_future': True,
                'verbose_name_plural': 'Bank Accounts',
            },
            bases=('basemodels.basemodel',),
        ),
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.BaseModel')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Bank Name',
                'manager_inheritance_from_future': True,
                'verbose_name_plural': 'Bank Names',
            },
            bases=('basemodels.basemodel',),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts_name', to='bankaccounts.BankName', verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='user_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
