# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bosdyn/api/spot_cam/compositor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from bosdyn.api.spot_cam import camera_pb2 as bosdyn_dot_api_dot_spot__cam_dot_camera__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bosdyn/api/spot_cam/compositor.proto',
  package='bosdyn.api.spot_cam',
  syntax='proto3',
  serialized_pb=_b('\n$bosdyn/api/spot_cam/compositor.proto\x12\x13\x62osdyn.api.spot_cam\x1a\x17\x62osdyn/api/header.proto\x1a bosdyn/api/spot_cam/camera.proto\"!\n\x11ScreenDescription\x12\x0c\n\x04name\x18\x01 \x01(\t\"=\n\x10GetScreenRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"M\n\x11GetScreenResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x0c\n\x04name\x18\x02 \x01(\t\"E\n\x18GetVisibleCamerasRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"\xe0\x02\n\x19GetVisibleCamerasResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x46\n\x07streams\x18\x02 \x03(\x0b\x32\x35.bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream\x1a\xce\x01\n\x06Stream\x12L\n\x06window\x18\x01 \x01(\x0b\x32<.bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window\x12+\n\x06\x63\x61mera\x18\x02 \x01(\x0b\x32\x1b.bosdyn.api.spot_cam.Camera\x1aI\n\x06Window\x12\x0f\n\x07xoffset\x18\x01 \x01(\x05\x12\x0f\n\x07yoffset\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"?\n\x12ListScreensRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"z\n\x13ListScreensResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x37\n\x07screens\x18\x02 \x03(\x0b\x32&.bosdyn.api.spot_cam.ScreenDescription\"K\n\x10SetScreenRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x0c\n\x04name\x18\x02 \x01(\t\"M\n\x11SetScreenResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x0c\n\x04name\x18\x02 \x01(\tB\x11\x42\x0f\x43ompositorProtob\x06proto3')
  ,
  dependencies=[bosdyn_dot_api_dot_header__pb2.DESCRIPTOR,bosdyn_dot_api_dot_spot__cam_dot_camera__pb2.DESCRIPTOR,])




_SCREENDESCRIPTION = _descriptor.Descriptor(
  name='ScreenDescription',
  full_name='bosdyn.api.spot_cam.ScreenDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.spot_cam.ScreenDescription.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=153,
)


_GETSCREENREQUEST = _descriptor.Descriptor(
  name='GetScreenRequest',
  full_name='bosdyn.api.spot_cam.GetScreenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.GetScreenRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=216,
)


_GETSCREENRESPONSE = _descriptor.Descriptor(
  name='GetScreenResponse',
  full_name='bosdyn.api.spot_cam.GetScreenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.GetScreenResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.spot_cam.GetScreenResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=295,
)


_GETVISIBLECAMERASREQUEST = _descriptor.Descriptor(
  name='GetVisibleCamerasRequest',
  full_name='bosdyn.api.spot_cam.GetVisibleCamerasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.GetVisibleCamerasRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=366,
)


_GETVISIBLECAMERASRESPONSE_STREAM_WINDOW = _descriptor.Descriptor(
  name='Window',
  full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='xoffset', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window.xoffset', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yoffset', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window.yoffset', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=648,
  serialized_end=721,
)

_GETVISIBLECAMERASRESPONSE_STREAM = _descriptor.Descriptor(
  name='Stream',
  full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='window', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.window', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='camera', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.camera', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETVISIBLECAMERASRESPONSE_STREAM_WINDOW, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=721,
)

_GETVISIBLECAMERASRESPONSE = _descriptor.Descriptor(
  name='GetVisibleCamerasResponse',
  full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='streams', full_name='bosdyn.api.spot_cam.GetVisibleCamerasResponse.streams', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_GETVISIBLECAMERASRESPONSE_STREAM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=721,
)


_LISTSCREENSREQUEST = _descriptor.Descriptor(
  name='ListScreensRequest',
  full_name='bosdyn.api.spot_cam.ListScreensRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.ListScreensRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=723,
  serialized_end=786,
)


_LISTSCREENSRESPONSE = _descriptor.Descriptor(
  name='ListScreensResponse',
  full_name='bosdyn.api.spot_cam.ListScreensResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.ListScreensResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='screens', full_name='bosdyn.api.spot_cam.ListScreensResponse.screens', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=788,
  serialized_end=910,
)


_SETSCREENREQUEST = _descriptor.Descriptor(
  name='SetScreenRequest',
  full_name='bosdyn.api.spot_cam.SetScreenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.SetScreenRequest.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.spot_cam.SetScreenRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=912,
  serialized_end=987,
)


_SETSCREENRESPONSE = _descriptor.Descriptor(
  name='SetScreenResponse',
  full_name='bosdyn.api.spot_cam.SetScreenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='bosdyn.api.spot_cam.SetScreenResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='bosdyn.api.spot_cam.SetScreenResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=989,
  serialized_end=1066,
)

_GETSCREENREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_GETSCREENRESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
_GETVISIBLECAMERASREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_GETVISIBLECAMERASRESPONSE_STREAM_WINDOW.containing_type = _GETVISIBLECAMERASRESPONSE_STREAM
_GETVISIBLECAMERASRESPONSE_STREAM.fields_by_name['window'].message_type = _GETVISIBLECAMERASRESPONSE_STREAM_WINDOW
_GETVISIBLECAMERASRESPONSE_STREAM.fields_by_name['camera'].message_type = bosdyn_dot_api_dot_spot__cam_dot_camera__pb2._CAMERA
_GETVISIBLECAMERASRESPONSE_STREAM.containing_type = _GETVISIBLECAMERASRESPONSE
_GETVISIBLECAMERASRESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
_GETVISIBLECAMERASRESPONSE.fields_by_name['streams'].message_type = _GETVISIBLECAMERASRESPONSE_STREAM
_LISTSCREENSREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_LISTSCREENSRESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
_LISTSCREENSRESPONSE.fields_by_name['screens'].message_type = _SCREENDESCRIPTION
_SETSCREENREQUEST.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._REQUESTHEADER
_SETSCREENRESPONSE.fields_by_name['header'].message_type = bosdyn_dot_api_dot_header__pb2._RESPONSEHEADER
DESCRIPTOR.message_types_by_name['ScreenDescription'] = _SCREENDESCRIPTION
DESCRIPTOR.message_types_by_name['GetScreenRequest'] = _GETSCREENREQUEST
DESCRIPTOR.message_types_by_name['GetScreenResponse'] = _GETSCREENRESPONSE
DESCRIPTOR.message_types_by_name['GetVisibleCamerasRequest'] = _GETVISIBLECAMERASREQUEST
DESCRIPTOR.message_types_by_name['GetVisibleCamerasResponse'] = _GETVISIBLECAMERASRESPONSE
DESCRIPTOR.message_types_by_name['ListScreensRequest'] = _LISTSCREENSREQUEST
DESCRIPTOR.message_types_by_name['ListScreensResponse'] = _LISTSCREENSRESPONSE
DESCRIPTOR.message_types_by_name['SetScreenRequest'] = _SETSCREENREQUEST
DESCRIPTOR.message_types_by_name['SetScreenResponse'] = _SETSCREENRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScreenDescription = _reflection.GeneratedProtocolMessageType('ScreenDescription', (_message.Message,), dict(
  DESCRIPTOR = _SCREENDESCRIPTION,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.ScreenDescription)
  ))
_sym_db.RegisterMessage(ScreenDescription)

GetScreenRequest = _reflection.GeneratedProtocolMessageType('GetScreenRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETSCREENREQUEST,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetScreenRequest)
  ))
_sym_db.RegisterMessage(GetScreenRequest)

GetScreenResponse = _reflection.GeneratedProtocolMessageType('GetScreenResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETSCREENRESPONSE,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetScreenResponse)
  ))
_sym_db.RegisterMessage(GetScreenResponse)

GetVisibleCamerasRequest = _reflection.GeneratedProtocolMessageType('GetVisibleCamerasRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVISIBLECAMERASREQUEST,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetVisibleCamerasRequest)
  ))
_sym_db.RegisterMessage(GetVisibleCamerasRequest)

GetVisibleCamerasResponse = _reflection.GeneratedProtocolMessageType('GetVisibleCamerasResponse', (_message.Message,), dict(

  Stream = _reflection.GeneratedProtocolMessageType('Stream', (_message.Message,), dict(

    Window = _reflection.GeneratedProtocolMessageType('Window', (_message.Message,), dict(
      DESCRIPTOR = _GETVISIBLECAMERASRESPONSE_STREAM_WINDOW,
      __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
      # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream.Window)
      ))
    ,
    DESCRIPTOR = _GETVISIBLECAMERASRESPONSE_STREAM,
    __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
    # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetVisibleCamerasResponse.Stream)
    ))
  ,
  DESCRIPTOR = _GETVISIBLECAMERASRESPONSE,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.GetVisibleCamerasResponse)
  ))
_sym_db.RegisterMessage(GetVisibleCamerasResponse)
_sym_db.RegisterMessage(GetVisibleCamerasResponse.Stream)
_sym_db.RegisterMessage(GetVisibleCamerasResponse.Stream.Window)

ListScreensRequest = _reflection.GeneratedProtocolMessageType('ListScreensRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTSCREENSREQUEST,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.ListScreensRequest)
  ))
_sym_db.RegisterMessage(ListScreensRequest)

ListScreensResponse = _reflection.GeneratedProtocolMessageType('ListScreensResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTSCREENSRESPONSE,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.ListScreensResponse)
  ))
_sym_db.RegisterMessage(ListScreensResponse)

SetScreenRequest = _reflection.GeneratedProtocolMessageType('SetScreenRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETSCREENREQUEST,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.SetScreenRequest)
  ))
_sym_db.RegisterMessage(SetScreenRequest)

SetScreenResponse = _reflection.GeneratedProtocolMessageType('SetScreenResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETSCREENRESPONSE,
  __module__ = 'bosdyn.api.spot_cam.compositor_pb2'
  # @@protoc_insertion_point(class_scope:bosdyn.api.spot_cam.SetScreenResponse)
  ))
_sym_db.RegisterMessage(SetScreenResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\017CompositorProto'))
# @@protoc_insertion_point(module_scope)
