# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-05 14:24


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20181104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\\u0632\\u0645\\u0627\\u0646'),
        ),
        migrations.AlterField(
            model_name='coursesummary',
            name='total_time_seconds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='\\u0632\\u0645\\u0627\\u0646'),
        ),
    ]
