
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-31T11:19:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "deb2e92dad1ae727ca3337ac44bdc5d2ce7cfa7b",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
