# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-03 12:42


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segments', '0002_auto_20181026_1745'),
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworkSegment',
            fields=[
                ('basesegment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='segments.BaseSegment')),
            ],
            options={
                'verbose_name': 'Social Segment',
                'manager_inheritance_from_future': True,
                'verbose_name_plural': 'Social Segments',
            },
            bases=('segments.basesegment',),
        ),
    ]
