# Generated by Django 2.2.12 on 2020-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='foreign_key',
            field=models.IntegerField(blank=True, db_index=True, default=None, help_text='ID of a record in another table that this file belongs to', null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='foreign_table',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='table or model that this file belongs to', max_length=100, null=True),
        ),
    ]
