
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T18:49:24+0530",
 "dirty": true,
 "error": null,
 "full-revisionid": "6943b1d618b10a5ff16c6708d72c6a319ff0a444",
 "version": "1.8.1.post7.dev0+g6943b1d"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
