# Generated by Django 2.2.15 on 2020-11-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psu_upload', '0003_auto_20201118_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasefile',
            name='filename',
        ),
        migrations.AddField(
            model_name='databasefile',
            name='basename',
            field=models.CharField(db_index=True, default='Unnamed', help_text='File name without the path info', max_length=128),
        ),
        migrations.AddField(
            model_name='databasefile',
            name='s3_path',
            field=models.CharField(default='Unnamed', help_text='Full S3 file path', max_length=256),
        ),
    ]
