#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['stardustlib']

package_data = \
{'': ['*']}

setup(name='stardustlib',
      version='0.0.1',
      description='Package to interact with the stardust database.',
      author='Reto Trappitsch',
      author_email='reto@galactic-forensics.space',
      url='https://github.com/galactic-forensics/stardustlib',
      packages=packages,
      package_data=package_data,
     )
