# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.network import Network  # noqa: E501
from elements_sdk.rest import ApiException

class TestNetwork(unittest.TestCase):
    """Network unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Network
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.network.Network()  # noqa: E501
        if include_optional :
            return Network(
                id = 56, 
                name = '0', 
                address = '0', 
                use_for_mounts = True, 
                priority = -2147483648
            )
        else :
            return Network(
                name = '0',
                address = '0',
        )

    def testNetwork(self):
        """Test Network"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
