# coding: utf-8

"""
    ELEMENTS API

    The version of the OpenAPI document: 2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import elements_sdk
from elements_sdk.models.alert import Alert  # noqa: E501
from elements_sdk.rest import ApiException

class TestAlert(unittest.TestCase):
    """Alert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Alert
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = elements_sdk.models.alert.Alert()  # noqa: E501
        if include_optional :
            return Alert(
                id = 56, 
                name = '0', 
                message = '0', 
                level = '0', 
                is_open = True, 
                node_id = '0', 
                opened_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                closed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                duration = '0'
            )
        else :
            return Alert(
                name = '0',
                message = '0',
                level = '0',
                is_open = True,
        )

    def testAlert(self):
        """Test Alert"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
