# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-04-28 16:47


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20190428_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecourse',
            name='content',
        ),
    ]
