# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-11 15:52


from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0007_auto_20181211_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, help_text='Enter a comma-separated tag string', to='basemodels.Tag'),
        ),
    ]
