# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-17 14:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('IRR', 'IRR'), ('D', 'Dollar')], default='IRR', max_length=10, verbose_name='Currency'),
        ),
    ]
