# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['try', 'except', 'img']

# Cell
# from nbdev.showdoc import *
import os
from pathlib import Path

# Cell
try:
    p = Path(os.path.abspath(__file__)).parent
except:
    p = Path(os.getcwd()) / 'cc_nbdev_template'
print(p)
img = p / "t.jpg"
with img.open('rb') as f:
    data = f.read()
print(len(data))