# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 18:29


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190613_1815'),
        ('questionanswers', '0005_auto_20190613_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basereview',
            name='model_obj',
        ),
        migrations.AlterField(
            model_name='review',
            name='model_obj2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='basemodels.BaseModel', verbose_name='Model'),
            preserve_default=False,
        ),
    ]
