
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T10:00:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "94b18009b3c3866a563cdf224b42b6b1d656896d",
 "version": "2.4.24.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
