
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-09T15:30:12+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "efd5684be1e05a976721873135e05107ec73584c",
 "version": "2.0.50.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
