
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-20T19:31:19+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb7200c767b7a4858a0bdbf5e990eb9c5b069e90",
 "version": "0.4.1b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
