# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-04 10:52


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='seconds',
            field=models.CharField(default='0', max_length=255, verbose_name='\\u0632\\u0645\\u0627\\u0646'),
        ),
    ]
