
#
# ENCRYPTION KEY
#
ENCRYPTION_KEY_ENV_NAME = 'SZCZYPIOREK_ENCRYPTION_KEY'

ENCRYPTION_KEY_FILE_ENV_NAME = 'SZCZYPIOREK_ENCRYPTION_KEY_FILE'

ENCRYPTION_KEY_DEFAULT = '.szczypiorek_encryption_key'

#
# ENVRIONMENT GPG
#
ENVIRONMENT_GPG_ENV_NAME = 'SZCZYPIOREK_ENVIRONMENT_GPG'

ENVIRONMENT_GPG_FILE_ENV_NAME = 'SZCZYPIOREK_ENVIRONMENT_GPG_FILE'

ENVIRONMENT_GPG_DEFAULT = 'env.gpg'

#
# SETTINGS
#
ENCRYPTION_KEY_LENGTH = 128
