# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-02 10:55


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0003_basemodel_update_needed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_slider_segment_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSharing',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='basemodels.BaseModel')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('product_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsharing_product', to='products.Product', verbose_name='Product')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsharing_user_source', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('user_product_share_with_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsharing_user_product_share_with', to=settings.AUTH_USER_MODEL, verbose_name='Share With')),
            ],
            options={
                'verbose_name': 'Product Sharing',
                'verbose_name_plural': 'Products Sharing',
            },
            bases=('basemodels.basemodel',),
        ),
    ]
