
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-03T23:18:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e68ddf16ec1b87e07c2f7d59ccdbb480c2b9e4c4",
 "version": "0.6.2.post.dev50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
