
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-03T23:11:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "faee2036b7b34a4bbe873d79501fb3b8923aa7f6",
 "version": "0.6.2.post.dev48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
