
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-30T15:58:02+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2058e751b514fb55329f0d0281fd89e456d0987",
 "version": "2.0.48"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
