
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-04T12:05:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdc0a9d72bfb1584f10d9d0a4ba7c4e8a160bf25",
 "version": "0.0.3.post.dev9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
