# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-08 11:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slider_segment_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_percent',
            new_name='discount_percent_value',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent_expire',
            field=models.DateTimeField(blank=True, help_text='If blank, without expire', null=True, verbose_name='Discount Expire'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_discount_percent_expire_show',
            field=models.BooleanField(default=False, help_text='If True countdown is available', verbose_name='Is Discount Expire Show'),
        ),
    ]
