
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-05T03:44:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3c3a574fc1ca513aacb8bc9176c6b985df87fe2b",
 "version": "0.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
