# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-06-13 18:14


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0011_auto_20190612_1035'),
        ('questionanswers', '0003_auto_20181120_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='model_obj2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answers_set', to='basemodels.BaseModel', verbose_name='\\u0686\\u0647 \\u0686\\u06cc\\u0632 \\u0631\\u0627 \\u0646\\u0645\\u0627\\u06cc\\u0634 \\u062f\\u0647\\u062f\\u061f'),
        ),
    ]
