#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

extras_require = \
{":python_version < '3.5'": ['typing'], 'dev': ['pytest', 'pytest-cov']}

setup(name='aiorun',
      version='2020.12.1',
      description='Boilerplate for asyncio applications',
      author='Caleb Hattingh',
      author_email='caleb.hattingh@gmail.com',
      url='https://github.com/cjrh/aiorun',
      py_modules=['aiorun'],
      extras_require=extras_require,
      python_requires='>=3.5',
     )
