# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-28 21:18


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_slidersegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='pages',
        ),
    ]
