
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-06T01:29:37+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e21b38c1e6302f7b71784bdc5b8af7d3972e0f2",
 "version": "2.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
