
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-07T07:29:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa62585675291c31c4dd2fc28ec19f5f76ad9808",
 "version": "0.6.2.post.dev68"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
