
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-01T18:25:26-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bffe81aed56a374689c48cc4b9e5a851d7da97d",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
